Initial Tutorial Update
ml4wireless/adsb-nats pull request #24
Opened 2023-10-02 04:50 UTC by omairsalam

Miscallensous changes that I made while updating the docs. These include some annotations about things that weren't working, I will leave them there for the time being, since we might change our flow to not use them later.

To test this, I ran `npx docusaurus run` and the output looked good.

2023-10-04 02:52 UTC, joshsanz requested changes
I left a few comments, mostly for typos, then it should be good to go.

2023-10-04 02:52 UTC, joshsanz commented on docs-website/docs/local.md
> +    2. Locat the lsub library in the filesystem (this library might exist in multiple places, if so, any should work, as long as the version is correct)
Typo in "Locat[e]"

2023-10-04 02:52 UTC, joshsanz commented on docs-website/docs/local.md
> +6. If those don’t work and you get a libsub error try the below: (may need to point to library location of lusb/libusb)
Several libsub => libusb, lsub => lusb below

2023-10-04 02:52 UTC, joshsanz commented on docs-website/versioned_docs/version-1.0.2/local.md
> +#### macos
macos => macOS

2023-10-04 02:52 UTC, joshsanz commented on docs-website/versioned_docs/version-1.0.2/local.md
> +6. If those don’t work and you get a libsub error try the below: (may need to point to library location of lusb/libusb)
Several libsub and lsub => usb typos below

2023-10-04 02:52 UTC, joshsanz commented on docs-website/versioned_docs/version-1.0.2/local.md
> +    - <IP_ADDRESS_AND_PORT> comes from the last few lines of output when starting the Kubernetes server above. So, nagivate to that termina window and copy one of the IP and port combinations on whic
Termina[l]

2023-10-04 02:52 UTC, joshsanz commented on docs-website/versioned_docs/version-1.0.2/replicate/aws.md
> +# Get the credentials for your cluster -- THIS DIDN'T WORK FOR ME
If this step is unnecessary for the 2nd step, go ahead and remove it.

2023-10-04 02:52 UTC, joshsanz commented on docs-website/versioned_docs/version-1.0.2/replicate/aws.md
>  1. One-line installer creates a secure cluster named 'nats’
Here, I am not sure why the one-line installer is used. I think a helm deployment with a yaml configuration is much better. We can leave this as-is for now but once the new deployment mechanism is finalized it should be updated.

2023-10-04 02:52 UTC, joshsanz commented on docs-website/versioned_docs/version-1.0.2/replicate/client.md
> +    3. Do we not need to update the
Need to update the what?

2023-10-23 20:32 UTC, omairsalam commented on docs-website/versioned_docs/version-1.0.2/replicate/client.md
> +    3. Do we not need to update the
Accidental. Removed.

2023-10-23 20:40 UTC, merged